nome = str(input('Digite seu nome completo: ')).strip()
separa = nome.split()
print('.....Analisando seu nome .....')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúscula é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu primeiro nome é {} ele tem {} letras'.format(separa[0], len(separa[0])))
print('..............................')
print('Programado By Elias')